# Generated by Django 4.2.30 on 2026-06-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeerecord",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="employmentcontract",
            options={"ordering": ["-start_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leavetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="payrollslip",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="performancereview",
            options={"ordering": ["-review_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="staffattendance",
            options={"ordering": ["-date", "-id"]},
        ),
    ]
