# Generated by Django 4.2.30 on 2026-06-30 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "event_name",
                    models.CharField(
                        help_text="Triggering Event e.g. 'Payment Received'",
                        max_length=150,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text='List of IF conditions e.g. [{"field": "amount", "op": ">=", "val": 1000}]',
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=list,
                        help_text='List of THEN actions e.g. [{"type": "notify", "target": "student"}]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        help_text="attendance_reminder, weekly_report, monthly_finance, certificate_gen, db_cleanup, backup_verify",
                        max_length=100,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(default="0 0 * * *", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("execution_log", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Scheduled Job",
                "verbose_name_plural": "Scheduled Jobs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Admissions", "Admissions"),
                            ("Finance", "Finance"),
                            ("Academic", "Academic"),
                            ("Lesson", "Lesson"),
                            ("Exam", "Exam"),
                            ("Certificate", "Certificate"),
                            ("Communication", "Communication"),
                            ("HR", "HR"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event-Driven"),
                            ("SCHEDULED", "Scheduled (Cron)"),
                            ("MANUAL", "Manual Trigger"),
                        ],
                        default="EVENT",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        help_text="Event name triggering this workflow e.g. 'Payment Received'",
                        max_length=150,
                    ),
                ),
                (
                    "trigger_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron schedule if scheduled",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAFT", "Draft"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "definition_json",
                    models.JSONField(
                        default=dict,
                        help_text="Nodes and edges visual workflow definition",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Definition",
                "verbose_name_plural": "Workflow Definitions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("WAITING_APPROVAL", "Waiting for Approval"),
                            ("CANCELLED", "Cancelled"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="RUNNING",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        default=dict, help_text="Initial payload/event data"
                    ),
                ),
                (
                    "execution_context",
                    models.JSONField(
                        default=dict, help_text="Accumulated state and variables"
                    ),
                ),
                ("current_step_id", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("initiator", models.CharField(default="System", max_length=200)),
                ("error_message", models.TextField(blank=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_id", models.CharField(max_length=100)),
                ("step_name", models.CharField(max_length=200)),
                ("action_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="SUCCESS",
                        max_length=30,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("duration_ms", models.IntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("error_details", models.TextField(blank=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action Log",
                "verbose_name_plural": "Workflow Action Logs",
                "ordering": ["executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "target_role",
                    models.CharField(
                        blank=True,
                        help_text="e.g., admin, accountant, hr, registrar, admissions",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="workflows.workflowinstance",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Request",
                "verbose_name_plural": "Approval Requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
