# Generated by Django 4.2.30 on 2026-06-29 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "communication",
            "0002_conversation_created_by_conversation_is_archived_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("IMPORTANT", "Important"),
                    ("URGENT", "Urgent"),
                    ("EMERGENCY", "Emergency"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="course_channel",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[
                    ("DIRECT", "Direct Messaging"),
                    ("GROUP", "Group Chat"),
                    ("COURSE", "Course Discussion"),
                ],
                default="DIRECT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="communication.privatemessage",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True, related_name="starred_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="communicationauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Message Created"),
                    ("EDITED", "Message Edited"),
                    ("DELETED", "Message Deleted"),
                    ("READ", "Message Read"),
                    ("AI_REQUEST", "AI Assistant Query"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="UserCommunicationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presence_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("AWAY", "Away"),
                            ("BUSY", "Busy"),
                            ("OFFLINE", "Offline"),
                            ("DND", "Do Not Disturb"),
                        ],
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("custom_status", models.CharField(blank=True, max_length=100)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("mute_all", models.BooleanField(default=False)),
                ("mute_messages", models.BooleanField(default=False)),
                ("mute_announcements", models.BooleanField(default=False)),
                ("mute_ai", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationPermissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_role", models.CharField(max_length=50)),
                ("target_role", models.CharField(max_length=50)),
                ("is_allowed", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Communication Permission Policies",
                "unique_together": {("sender_role", "target_role")},
            },
        ),
    ]
