# Generated by Django 4.2.30 on 2026-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "communication",
            "0003_announcement_priority_announcement_scheduled_for_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="entity_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="conversation",
            name="entity_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[
                    ("DIRECT", "Direct Chat"),
                    ("GROUP", "Department Group"),
                    ("COURSE", "Course Discussion"),
                    ("CLASS", "Class Discussion"),
                    ("COMMITTEE", "Committee"),
                    ("TICKET", "Support Ticket"),
                    ("FINANCE_THREAD", "Finance Thread"),
                    ("ADMISSIONS_THREAD", "Admissions Thread"),
                    ("PARENT_DISCUSSION", "Parent Discussion"),
                    ("HR", "HR"),
                    ("ICT", "ICT"),
                    ("AI_ASSISTANT", "AI Assistant"),
                    ("INSTITUTION_ANNOUNCEMENTS", "Institution Announcements"),
                    ("EMERGENCY_BROADCAST", "Emergency Broadcast"),
                ],
                default="DIRECT",
                max_length=35,
            ),
        ),
    ]
