# Generated by Django 4.2.30 on 2026-06-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("HUGGINGFACE", "Hugging Face Inference API"),
                            ("OPENAI", "OpenAI API"),
                            ("GEMINI", "Google Gemini"),
                            ("OLLAMA", "Local Ollama"),
                        ],
                        default="HUGGINGFACE",
                        max_length=50,
                    ),
                ),
                (
                    "huggingface_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key or Token for Hugging Face Inference API",
                        max_length=255,
                    ),
                ),
                ("openai_api_key", models.CharField(blank=True, max_length=255)),
                ("gemini_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "model_name",
                    models.CharField(
                        default="mistralai/Mistral-7B-Instruct-v0.3",
                        help_text="Primary LLM Model Name",
                        max_length=150,
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=768)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are Antigravity AI, the official intelligent RAG chatbot for Horizon Deutsch Training Institute ERP. Answer strictly based on the retrieved context and institutional knowledge provided. If unsure, advise contacting support."
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="sentence-transformers/all-MiniLM-L6-v2", max_length=150
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI System Configuration",
                "verbose_name_plural": "AI System Configuration",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FAQ", "Frequently Asked Questions"),
                            ("POLICY", "Institution Policy & Rules"),
                            ("COURSE_NOTE", "Course / Syllabus Note"),
                            ("ANNOUNCEMENT", "Public Announcement"),
                            ("GENERAL", "General Knowledge"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full text content indexed for semantic search"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional source PDF/Word document",
                        null=True,
                        upload_to="knowledge_base/",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stored float vector array for cosine similarity",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_role", models.CharField(blank=True, max_length=50)),
                ("question", models.TextField()),
                ("retrieved_context", models.TextField(blank=True)),
                ("model_used", models.CharField(max_length=150)),
                ("response_text", models.TextField()),
                ("response_time_ms", models.IntegerField(default=0)),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("HELPFUL", "👍 Helpful"),
                            ("NOT_HELPFUL", "👎 Not Helpful"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
