# Generated by Django 4.2.30 on 2026-06-30 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestlog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="indexing_status",
            field=models.CharField(
                default="INDEXED", help_text="INDEXED, PENDING, FAILED", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("FAQ", "Frequently Asked Questions"),
                    ("POLICY", "Institution Policy & Rules"),
                    ("COURSE_NOTE", "Course / Syllabus Note"),
                    ("ANNOUNCEMENT", "Public Announcement"),
                    ("GENERAL", "General Knowledge"),
                    ("LESSON_PDF", "Lesson PDF"),
                    ("LESSON_DOCX", "Lesson DOCX"),
                    ("PPT", "PowerPoint Presentation"),
                    ("TEACHER_NOTE", "Teacher Notes"),
                    ("HANDBOOK", "Student Handbook"),
                    ("REGULATION", "Academic Regulations"),
                    ("BLOG", "Institutional Blog"),
                    ("MEMO", "Memorandum"),
                    ("FORM", "Institutional Form"),
                ],
                default="GENERAL",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeIndexingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_type", models.CharField(default="PDF", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexing_jobs",
                        to="ai_assistant.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AIConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="airequestlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_assistant.aiconversationsession",
            ),
        ),
    ]
