# Generated by Django 4.2.30 on 2026-06-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0004_student_advisor_student_career_pathway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Horizon Deutsch Training Institute", max_length=200
                    ),
                ),
                ("abbreviation", models.CharField(default="HDTI", max_length=20)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("phone_primary", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("email_primary", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True)),
                ("postal_address", models.TextField(blank=True)),
                ("physical_address", models.TextField(blank=True)),
                ("facebook_link", models.URLField(blank=True)),
                ("instagram_link", models.URLField(blank=True)),
                ("tiktok_link", models.URLField(blank=True)),
                ("twitter_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("google_maps_link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Institution Profile",
                "verbose_name_plural": "Institution Profile",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Admissions", "Admissions"),
                            ("Finance", "Finance"),
                            ("Academic", "Academic"),
                            ("Technical Support", "Technical Support"),
                            ("Visa Guidance", "Visa Guidance"),
                            ("Career Guidance", "Career Guidance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
