# Generated by Django 4.2.30 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_request_id", models.CharField(max_length=100, unique=True)),
                ("merchant_request_id", models.CharField(max_length=100, unique=True)),
                (
                    "mpesa_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("FINAL", "Final"), ("VOID", "Void")],
                default="DRAFT",
                max_length=15,
            ),
        ),
    ]
