# Generated by Django 4.2.30 on 2026-06-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("finance", "0002_mpesatransaction_alter_receipt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpesa_transactions",
                to="students.student",
            ),
        ),
    ]
