# Generated by Django 4.2.30 on 2026-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_mpesatransaction_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mpesatransaction",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_relationship",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
