# Generated by Django 4.2.30 on 2026-06-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0002_student_campus_student_deleted_at_student_is_deleted_and_more",
        ),
        ("finance", "0004_allocation_deleted_at_allocation_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Fee Charge", "Fee Charge"),
                            ("Payment", "Payment"),
                            ("Allocation", "Allocation"),
                            ("Adjustment", "Adjustment"),
                            ("Refund", "Refund"),
                            ("Credit", "Credit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
