# Generated by Django 4.2.30 on 2026-06-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lesson-resources", "Lesson Resources"),
                            ("knowledge-base", "Knowledge Base"),
                            ("assignments", "Assignments"),
                            ("assignment-submissions", "Assignment Submissions"),
                            ("student-documents", "Student Documents"),
                            ("staff-documents", "Staff Documents"),
                            ("institution-policies", "Institution Policies"),
                            ("student-handbook", "Student Handbook"),
                            ("staff-handbook", "Staff Handbook"),
                            ("blogs", "Blogs"),
                            ("news", "News"),
                            ("announcements", "Announcements"),
                            ("downloads", "Downloads"),
                            ("certificates", "Certificates"),
                            ("receipts", "Receipts"),
                            ("student-ids", "Student IDs"),
                            ("exam-cards", "Exam Cards"),
                            ("transcripts", "Transcripts"),
                            ("gallery", "Gallery"),
                            ("system-assets", "System Assets"),
                            ("germany-info", "Germany Information"),
                            ("visa-info", "Visa Information"),
                            ("ausbildung", "Ausbildung"),
                            ("au-pair", "Au Pair"),
                            ("faqs", "FAQs"),
                            ("academic-calendar", "Academic Calendar"),
                        ],
                        default="knowledge-base",
                        max_length=60,
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(
                        help_text="Logical folder path in Supabase Storage",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="dms_storage/"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("PPT", "PowerPoint Presentation"),
                            ("WORD", "Word Document"),
                            ("IMAGE", "Image File"),
                            ("AUDIO", "Audio Recording"),
                            ("VIDEO", "Video Recording"),
                            ("ZIP", "Compressed Archive"),
                            ("LINK", "External / YouTube / Google Drive Link"),
                        ],
                        default="PDF",
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="YouTube or Google Drive URL if applicable",
                        max_length=500,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                ("keywords", models.CharField(blank=True, max_length=255)),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        help_text="Course identifier or name",
                        max_length=100,
                    ),
                ),
                (
                    "lesson",
                    models.CharField(
                        blank=True, help_text="Lesson title or ID", max_length=100
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, help_text="CEFR band e.g. A1, B2", max_length=50
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone)"),
                            ("STUDENTS", "All Enrolled Students"),
                            ("TEACHERS", "Teachers Only"),
                            ("ADMIN", "Administrators Only"),
                            ("COURSE_ONLY", "Enrolled Course Students Only"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_indexed", models.BooleanField(default=False)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text extracted for AI semantic RAG search",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Metadata",
                "verbose_name_plural": "Document Metadata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="dms_archive/"),
                ),
                ("change_summary", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="dms.documentmetadata",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="DMSAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Upload"),
                            ("DOWNLOAD", "Download"),
                            ("VIEW", "View"),
                            ("EDIT", "Edit"),
                            ("DELETE", "Delete"),
                            ("RESTORE", "Restore"),
                            ("AI_SEARCH", "AI Search"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dms.documentmetadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
