# Generated by Django 4.2.30 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
