# Generated by Django 4.2.30 on 2026-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
