# Generated by Django 4.2.30 on 2026-06-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_admissionapplication_assigned_officer_and_more"),
        ("academics", "0007_virtualclass_host_link_virtualclass_is_recurring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("certificates", "0003_certificate_deleted_at_certificate_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("COURSE_COMPLETION", "Course Completion Certificate"),
                            ("CEFR_LEVEL", "CEFR Level Completion Certificate"),
                            ("PARTICIPATION", "Participation Certificate"),
                            ("ACHIEVEMENT", "Achievement Certificate"),
                        ],
                        default="CEFR_LEVEL",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institution_name",
                    models.CharField(
                        default="Horizon Deutsch Training Institute", max_length=200
                    ),
                ),
                ("header_text", models.CharField(default="ZERTIFIKAT", max_length=255)),
                (
                    "subtitle_text",
                    models.CharField(
                        default="CERTIFICATE OF COMPLETION", max_length=255
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        default="This is to certify that {student_name} has successfully completed the German Language Course and met all examination requirements for level {level_name} ({level_code})."
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="Authorized by Horizon Deutsch Institute Board",
                        max_length=255,
                    ),
                ),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("seal_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "signature_name",
                    models.CharField(default="Dr. Klaus Weber", max_length=100),
                ),
                (
                    "signature_title",
                    models.CharField(default="Academic Director", max_length=100),
                ),
                (
                    "signature_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "background_style",
                    models.CharField(default="CLASSIC_BORDER", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("COURSE_COMPLETION", "Course Completion Certificate"),
                    ("CEFR_LEVEL", "CEFR Level Completion Certificate"),
                    ("PARTICIPATION", "Participation Certificate"),
                    ("ACHIEVEMENT", "Achievement Certificate"),
                ],
                default="CEFR_LEVEL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/pdfs/"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="reissue_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="reissued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="reissued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reissued_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revocation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("student", "level", "certificate_type")},
        ),
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_certificates",
                to="certificates.certificatetemplate",
            ),
        ),
    ]
