# Generated by Django 4.2.30 on 2026-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_device",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("TUTOR", "Tutor"),
                    ("REGISTRAR", "Registrar"),
                    ("ACCOUNTANT", "Accountant"),
                    ("FINANCE", "Finance"),
                    ("ADMISSIONS", "Admissions"),
                    ("HR", "HR"),
                    ("LIBRARY", "Library"),
                    ("ICT", "ICT"),
                    ("ADMIN", "Admin"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
