# Generated by Django 4.2.30 on 2026-06-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_custom_permissions_user_is_2fa_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent"),
                    ("TEACHER", "Teacher"),
                    ("TUTOR", "Tutor"),
                    ("REGISTRAR", "Registrar"),
                    ("ACCOUNTANT", "Accountant"),
                    ("FINANCE", "Finance"),
                    ("ADMISSIONS", "Admissions"),
                    ("HR", "HR"),
                    ("LIBRARY", "Library"),
                    ("ICT", "ICT"),
                    ("ADMIN", "Admin"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
