# Generated by Django 4.2.30 on 2026-06-11 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionhistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TEACHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohorts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohorts",
                to="academics.level",
            ),
        ),
    ]
