# Generated by Django 4.2.30 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionhistory",
            name="remarks",
            field=models.TextField(blank=True),
        ),
    ]
