# Generated by Django 4.2.30 on 2026-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_promotionhistory_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Campuses",
            },
        ),
    ]
