# Generated by Django 4.2.30 on 2026-06-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "students",
            "0005_rename_documents_uploaded_admissionapplication_documents_verified_and_more",
        ),
        ("academics", "0005_careerpathway_externalexam_intake_virtualclass_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="level",
            name="cefr_category",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="level",
            name="parent_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_levels",
                to="academics.level",
            ),
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="academics.semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT", "Enrollment"),
                            ("PROMOTION", "Promotion"),
                            ("REPEAT", "Repeat"),
                            ("EXAM_PASSED", "Exam Passed"),
                            ("EXAM_FAILED", "Exam Failed"),
                            ("DISCIPLINARY", "Disciplinary"),
                            ("ADVISING", "Advising Session"),
                            ("FINANCIAL", "Financial Event"),
                            ("GRADUATION", "Graduation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_attendance_percentage", models.FloatField(default=80.0)),
                ("min_exam_score_percentage", models.FloatField(default=60.0)),
                ("min_assignments_completed", models.IntegerField(default=5)),
                ("allow_repeat_on_failure", models.BooleanField(default=True)),
                ("max_repeat_attempts", models.IntegerField(default=2)),
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_rule",
                        to="academics.level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("duration_months", models.IntegerField(default=6)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academics.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraduationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_total_credits", models.IntegerField(default=120)),
                ("require_fee_clearance", models.BooleanField(default=True)),
                ("require_library_clearance", models.BooleanField(default=True)),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_rule",
                        to="academics.program",
                    ),
                ),
                (
                    "required_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvisingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField()),
                ("action_items", models.TextField(blank=True)),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academics.advisor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advising_sessions",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
