# Generated by Django 4.2.30 on 2026-06-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_admissionapplication_assigned_officer_and_more"),
        (
            "academics",
            "0006_academicyear_department_semester_level_cefr_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualclass",
            name="host_link",
            field=models.URLField(
                blank=True, help_text="Host start URL for instructor"
            ),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="recording_url",
            field=models.URLField(blank=True, help_text="Replay video recording URL"),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("LIVE", "Live Now"),
                    ("ENDED", "Ended"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="student_join_link",
            field=models.URLField(
                blank=True, help_text="Direct join link for enrolled students"
            ),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="timezone",
            field=models.CharField(default="Africa/Nairobi", max_length=50),
        ),
        migrations.AddField(
            model_name="virtualclass",
            name="waiting_room",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="virtualclass",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Zoom", "Zoom"),
                    ("BBB", "BigBlueButton"),
                    ("Google Meet", "Google Meet"),
                    ("Teams", "Microsoft Teams"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="VirtualAttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("is_late", models.BooleanField(default=False)),
                ("connection_interruptions", models.PositiveIntegerField(default=0)),
                ("attendance_percentage", models.FloatField(default=100.0)),
                ("verified_by_teacher", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_attendances",
                        to="students.student",
                    ),
                ),
                (
                    "virtual_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="academics.virtualclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-join_time"],
                "unique_together": {("virtual_class", "student")},
            },
        ),
    ]
