# Generated by Django 4.2.30 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
