# Generated by Django 4.2.30 on 2026-06-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_campus"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.campus",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Dropped", "Dropped"),
                    ("Suspended", "Suspended"),
                    ("Inactive", "Inactive"),
                    ("Graduated", "Graduated"),
                    ("Transferred", "Transferred"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
