# Generated by Django 4.2.30 on 2026-06-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_careerpathway_externalexam_intake_virtualclass_and_more"),
        ("students", "0003_admissionapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisees",
                to="academics.advisor",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="career_pathway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.careerpathway",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="intake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.intake",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facebook", "Facebook"),
                    ("TikTok", "TikTok"),
                    ("Instagram", "Instagram"),
                    ("Google", "Google"),
                    ("Referral", "Referral"),
                    ("Staff Referral", "Staff Referral"),
                    ("Career Fair", "Career Fair"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
