# Generated by Django 4.2.30 on 2026-06-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_advisor_student_career_pathway_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admissionapplication",
            old_name="documents_uploaded",
            new_name="documents_verified",
        ),
        migrations.RenameField(
            model_name="admissionapplication",
            old_name="registration_fee_paid",
            new_name="previous_experience",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="applicant_name",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="campus",
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="academic_certificates",
            field=models.FileField(
                blank=True, null=True, upload_to="admissions/certificates/"
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="additional_documents",
            field=models.FileField(blank=True, null=True, upload_to="admissions/misc/"),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="career_pathway",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="county",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="current_german_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="current_occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="employer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="first_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="highest_education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="id_passport_document",
            field=models.FileField(blank=True, null=True, upload_to="admissions/ids/"),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="last_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="national_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="nationality",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="passport_photo",
            field=models.FileField(
                blank=True, null=True, upload_to="admissions/photos/"
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="postal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="preferred_campus",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="preferred_intake",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="preferred_schedule",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="professional_background",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="referral_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="study_mode",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="town",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Admissions Queue", "Admissions Queue"),
                    ("Document Verification", "Document Verification"),
                    ("Pending Test", "Pending Test"),
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Admissions Queue",
                max_length=50,
            ),
        ),
    ]
