# Generated by Django 4.2.30 on 2026-06-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0006_academicyear_department_semester_level_cefr_category_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0006_parentguardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionapplication",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                default="Normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="placement_tests",
                to="students.admissionapplication",
            ),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="grammar",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="listening",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="reading",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="speaking",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="vocabulary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placementtest",
            name="writing",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Admissions Queue", "Admissions Queue"),
                    ("Under Review", "Under Review"),
                    ("Documents Pending", "Documents Pending"),
                    ("Placement Test Pending", "Placement Test Pending"),
                    ("Interview Scheduled", "Interview Scheduled"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Deferred", "Deferred"),
                    ("Converted to Student", "Converted to Student"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="placementtest",
            name="recommended_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.level",
            ),
        ),
        migrations.AlterField(
            model_name="placementtest",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="placementtest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="placement_tests",
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="AdmissionsActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("old_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="students.admissionapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
