/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SessionTimeoutRouteImport } from './routes/session-timeout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as LoginStaffRouteImport } from './routes/login.staff'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppMarksRouteImport } from './routes/app.marks'
import { Route as AppFinanceReportsRouteImport } from './routes/app.finance-reports'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppFeeStructureRouteImport } from './routes/app.fee-structure'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/app.audit-logs'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAllocationsRouteImport } from './routes/app.allocations'
import { Route as AppAcademicRouteImport } from './routes/app.academic'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTimeoutRoute = SessionTimeoutRouteImport.update({
  id: '/session-timeout',
  path: '/session-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStaffRoute = LoginStaffRouteImport.update({
  id: '/login/staff',
  path: '/login/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksRoute = AppMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/finance-reports',
  path: '/finance-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFeeStructureRoute = AppFeeStructureRouteImport.update({
  id: '/fee-structure',
  path: '/fee-structure',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAllocationsRoute = AppAllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/academic': typeof AppAcademicRoute
  '/app/allocations': typeof AppAllocationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fee-structure': typeof AppFeeStructureRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/users': typeof AppUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/academic': typeof AppAcademicRoute
  '/app/allocations': typeof AppAllocationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fee-structure': typeof AppFeeStructureRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/users': typeof AppUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-timeout': typeof SessionTimeoutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/academic': typeof AppAcademicRoute
  '/app/allocations': typeof AppAllocationsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/fee-structure': typeof AppFeeStructureRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/users': typeof AppUsersRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/session-timeout'
    | '/unauthorized'
    | '/app/academic'
    | '/app/allocations'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/dashboard'
    | '/app/fee-structure'
    | '/app/finance'
    | '/app/finance-reports'
    | '/app/marks'
    | '/app/payments'
    | '/app/profile'
    | '/app/receipts'
    | '/app/reports'
    | '/app/results'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/users'
    | '/login/admin'
    | '/login/staff'
    | '/login/student'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/session-timeout'
    | '/unauthorized'
    | '/app/academic'
    | '/app/allocations'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/dashboard'
    | '/app/fee-structure'
    | '/app/finance'
    | '/app/finance-reports'
    | '/app/marks'
    | '/app/payments'
    | '/app/profile'
    | '/app/receipts'
    | '/app/reports'
    | '/app/results'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/users'
    | '/login/admin'
    | '/login/staff'
    | '/login/student'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/session-timeout'
    | '/unauthorized'
    | '/app/academic'
    | '/app/allocations'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/dashboard'
    | '/app/fee-structure'
    | '/app/finance'
    | '/app/finance-reports'
    | '/app/marks'
    | '/app/payments'
    | '/app/profile'
    | '/app/receipts'
    | '/app/reports'
    | '/app/results'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/users'
    | '/login/admin'
    | '/login/staff'
    | '/login/student'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SessionTimeoutRoute: typeof SessionTimeoutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginStaffRoute: typeof LoginStaffRoute
  LoginStudentRoute: typeof LoginStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-timeout': {
      id: '/session-timeout'
      path: '/session-timeout'
      fullPath: '/session-timeout'
      preLoaderRoute: typeof SessionTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/staff': {
      id: '/login/staff'
      path: '/login/staff'
      fullPath: '/login/staff'
      preLoaderRoute: typeof LoginStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks': {
      id: '/app/marks'
      path: '/marks'
      fullPath: '/app/marks'
      preLoaderRoute: typeof AppMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-reports': {
      id: '/app/finance-reports'
      path: '/finance-reports'
      fullPath: '/app/finance-reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fee-structure': {
      id: '/app/fee-structure'
      path: '/fee-structure'
      fullPath: '/app/fee-structure'
      preLoaderRoute: typeof AppFeeStructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/allocations': {
      id: '/app/allocations'
      path: '/allocations'
      fullPath: '/app/allocations'
      preLoaderRoute: typeof AppAllocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic': {
      id: '/app/academic'
      path: '/academic'
      fullPath: '/app/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRoute
  AppAllocationsRoute: typeof AppAllocationsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeeStructureRoute: typeof AppFeeStructureRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppMarksRoute: typeof AppMarksRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRoute,
  AppAllocationsRoute: AppAllocationsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeeStructureRoute: AppFeeStructureRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppMarksRoute: AppMarksRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SessionTimeoutRoute: SessionTimeoutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginStaffRoute: LoginStaffRoute,
  LoginStudentRoute: LoginStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
