# Generated by Django 4.2.30 on 2026-06-26 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "students",
            "0005_rename_documents_uploaded_admissionapplication_documents_verified_and_more",
        ),
        ("odel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionForum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_moderated", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("time_limit_minutes", models.PositiveIntegerField(default=30)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("randomize_questions", models.BooleanField(default=True)),
                ("negative_marking_percentage", models.FloatField(default=0.0)),
                ("pass_percentage", models.FloatField(default=60.0)),
                ("auto_submit_on_timer", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="is_sequential",
            field=models.BooleanField(
                default=True, help_text="Require sequential lesson completion"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="code_snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="completion_rule",
            field=models.CharField(
                choices=[
                    ("VIEW", "View"),
                    ("TIME", "Min Time"),
                    ("SCORE", "Pass Assessment"),
                ],
                default="VIEW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="min_time_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_modules",
                to="odel.course",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="is_bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="last_accessed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="reading_progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="resume_position_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="video_watch_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video Lecture"),
                    ("AUDIO", "Audio Track"),
                    ("PDF", "PDF Document"),
                    ("PPT", "PowerPoint Presentation"),
                    ("HTML", "Rich HTML Content"),
                    ("INTERACTIVE", "Interactive Exercise"),
                    ("SCORM", "SCORM Package"),
                    ("EXTERNAL_URL", "External URL"),
                    ("DOWNLOAD", "Downloadable File"),
                    ("EMBEDDED_YOUTUBE", "Embedded YouTube"),
                    ("IMAGE", "Image Graphic"),
                    ("CODE_SNIPPET", "Code Snippet"),
                ],
                default="VIDEO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="odel.unit",
            ),
        ),
        migrations.CreateModel(
            name="RecordedLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="odel/recordings/"
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "slides_file",
                    models.FileField(blank=True, null=True, upload_to="odel/slides/"),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_download_permitted", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_lectures",
                        to="odel.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("TRUE_FALSE", "True/False"),
                            ("MATCHING", "Matching"),
                            ("ESSAY", "Essay"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("FILL_BLANK", "Fill in the Blank"),
                            ("DRAG_DROP", "Drag & Drop"),
                        ],
                        default="MCQ",
                        max_length=20,
                    ),
                ),
                ("prompt_text", models.TextField()),
                (
                    "marks",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("options_json", models.JSONField(blank=True, default=list)),
                ("correct_answer_text", models.TextField(blank=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="odel.questionbank",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="odel.quiz",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="odel.lesson",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="odel.course",
            ),
        ),
        migrations.CreateModel(
            name="Gradebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continuous_assessment_weight", models.FloatField(default=40.0)),
                ("assignments_weight", models.FloatField(default=30.0)),
                ("quizzes_weight", models.FloatField(default=30.0)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook",
                        to="odel.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_question", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="odel.discussionforum",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_threads",
                        to="odel.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("is_approved_answer", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="odel.forumpost",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="odel.forumthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="discussionforum",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum",
                to="odel.course",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="odel/assignments/"
                    ),
                ),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("allow_late_submission", models.BooleanField(default=True)),
                ("late_penalty_percentage", models.FloatField(default=10.0)),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("rubric_text", models.TextField(blank=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="odel.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "score_obtained",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("answers_json", models.JSONField(blank=True, default=dict)),
                ("requires_manual_review", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="odel.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "file_submission",
                    models.FileField(
                        blank=True, null=True, upload_to="odel/submissions/"
                    ),
                ),
                ("rich_text_submission", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("GRADED", "Graded"),
                            ("RETURNED", "Returned for Revision"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="odel.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "student", "attempt_number")},
            },
        ),
    ]
