# Generated by Django 4.2.30 on 2026-06-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0007_admissionapplication_assigned_officer_and_more"),
        (
            "academics",
            "0006_academicyear_department_semester_level_cefr_category_and_more",
        ),
        ("odel", "0002_discussionforum_questionbank_quiz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialExamination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("exam_code", models.CharField(max_length=100, unique=True)),
                ("semester", models.CharField(default="Semester 1", max_length=100)),
                ("academic_year", models.CharField(default="2026", max_length=20)),
                (
                    "campus",
                    models.CharField(default="Nairobi Main Campus", max_length=100),
                ),
                ("cohort", models.CharField(blank=True, max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("GOETHE_MOCK", "Goethe-Zertifikat Mock Exam"),
                            ("MIDTERM", "Midterm Examination"),
                            ("FINAL", "Final Semester Examination"),
                            ("PLACEMENT", "Placement Test"),
                            ("CUSTOM", "Custom Assessment"),
                        ],
                        default="GOETHE_MOCK",
                        max_length=30,
                    ),
                ),
                (
                    "study_mode",
                    models.CharField(
                        default="Physical / Hybrid / Online", max_length=50
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                (
                    "maximum_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                (
                    "passing_marks",
                    models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
                ),
                ("exam_instructions", models.TextField(blank=True)),
                ("submission_instructions", models.TextField(blank=True)),
                (
                    "allowed_file_types",
                    models.CharField(
                        default="PDF, DOCX, JPG, PNG, ZIP", max_length=150
                    ),
                ),
                ("allowed_attempts", models.PositiveIntegerField(default=1)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "late_submission_policy",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow Late Submission"),
                            ("PENALTY", "Allow with Mark Penalty"),
                            ("REJECT", "Reject Late Submission"),
                        ],
                        default="ALLOW",
                        max_length=20,
                    ),
                ),
                ("late_penalty_percentage", models.FloatField(default=10.0)),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "exam_paper_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="odel/formal_exams/"
                    ),
                ),
                (
                    "marking_rubric",
                    models.FileField(blank=True, null=True, upload_to="odel/rubrics/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_exams",
                        to="odel.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_formal_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eligible_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_official_exams",
                        to="students.student",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_exams",
                        to="academics.level",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_exams",
                        to="odel.module",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ExamSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("browser_info", models.CharField(blank=True, max_length=255)),
                ("device_info", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("connection_interruptions", models.PositiveIntegerField(default=0)),
                ("focus_change_count", models.PositiveIntegerField(default=0)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("session_duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to="odel.officialexamination",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "uploaded_file",
                    models.FileField(upload_to="odel/formal_submissions/"),
                ),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_late", models.BooleanField(default=False)),
                (
                    "marked_script",
                    models.FileField(
                        blank=True, null=True, upload_to="odel/marked_scripts/"
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("teacher_feedback", models.TextField(blank=True)),
                (
                    "marking_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted / Pending Marking"),
                            ("UNDER_MARKING", "Under Marking"),
                            ("GRADED", "Graded"),
                            ("PUBLISHED", "Results Published"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="odel.officialexamination",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formal_exam_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("examination", "student", "attempt_number")},
            },
        ),
    ]
