# Generated by Django 4.2.30 on 2026-06-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0007_admissionapplication_assigned_officer_and_more"),
        ("odel", "0003_officialexamination_examsessionlog_examsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="Summary description of lesson"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="objectives",
            field=models.TextField(
                blank=True, help_text="Learning objectives or outcomes"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PUBLISHED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="checksum",
            field=models.CharField(
                blank=True, help_text="SHA-256 hash for deduplication", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="Extension e.g. pdf, docx, mp4", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="mime_type",
            field=models.CharField(
                blank=True, help_text="MIME type e.g. application/pdf", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="virus_scan_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Scan"),
                    ("CLEAN", "Clean"),
                    ("INFECTED", "Infected"),
                ],
                default="CLEAN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="notes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentlessonprogress",
            name="pages_viewed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StudentLessonNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("NOTE", "Personal Note"),
                            ("HIGHLIGHT", "Text Highlight"),
                            ("BOOKMARK", "Timestamp Bookmark"),
                        ],
                        default="NOTE",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content of the note or comment"
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(
                        blank=True, help_text="Highlighted excerpt from lesson body"
                    ),
                ),
                (
                    "timestamp_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Media playback position in seconds"
                    ),
                ),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="odel.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_notes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
