# Generated by Django 4.2.30 on 2026-06-30 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("odel", "0004_lesson_description_lesson_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmission",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Moderation"),
                    ("APPROVED", "Approved by Moderator"),
                    ("RETURNED", "Returned for Correction"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="moderator_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="examsubmission",
            name="student_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 Checksum of the examination file",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="file_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="mime_type",
            field=models.CharField(
                blank=True, default="application/pdf", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="supporting_files",
            field=models.FileField(
                blank=True, null=True, upload_to="odel/supporting_files/"
            ),
        ),
        migrations.AddField(
            model_name="officialexamination",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_official_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="officialexamination",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("GOETHE_MOCK", "Goethe-Zertifikat Mock Exam"),
                    ("MIDTERM", "Midterm Examination"),
                    ("FINAL", "Final Semester Examination"),
                    ("PLACEMENT", "Placement Test"),
                    ("CAT", "Continuous Assessment Test (CAT)"),
                    ("ORAL", "Oral Examination"),
                    ("LISTENING", "Listening Assessment"),
                    ("SPEAKING", "Speaking Assessment"),
                    ("READING", "Reading Assessment"),
                    ("WRITING", "Writing Assessment"),
                    ("CUSTOM", "Custom Assessment"),
                ],
                default="GOETHE_MOCK",
                max_length=30,
            ),
        ),
    ]
